import sys

with open("app.py", "r") as f:
    content = f.read()

replacements = {
    'Dashboard de Resultados': 'Results Dashboard',
    'Visualização interativa da correção de viés de rajadas de vento extremo.': 'Interactive visualization of extreme wind gust bias correction.',
    'Aba 1 — Explorador MLP': 'Tab 1 — MLP Explorer',
    'mapa de clusters + estações, série temporal, distribuição': 'cluster map + stations, time series, distribution',
    'scatter com regressão, métricas e importância de features': 'scatter with regression, metrics and feature importance',
    'Aba 2 — Screening LazyPredict': 'Tab 2 — LazyPredict Screening',
    'ranking dos 43 modelos avaliados por cluster': 'ranking of the 43 evaluated models per cluster',
    'Rajada máxima': 'Maximum Gust',
    'Varre ``base/exp*`` e monta a lista de experimentos. Fallback: usa o': 'Scans ``base/exp*`` and builds the list of experiments. Fallback: uses the',
    'diretório plano ``base`` como experimento único "(raiz)".': 'flat directory ``base`` as a single experiment "(root)".',
    '"(raiz)"': '"(root)"',
    'primeiro experimento (exp1 = baseline)': 'first experiment (exp1 = baseline)',
    '"(nenhum)"': '"(none)"',
    'Correção de viés de rajadas de vento extremo': 'Extreme wind gust bias correction',
    'Correção de Viés de Rajadas de Vento Extremo': 'Extreme Wind Gust Bias Correction',
    '"(nenhuma)"': '"(none)"',
    '"Estação"': '"Station"',
    '"Estações"': '"Stations"',
    '"**Split temporal**"': '"**Temporal Split**"',
    '"Treino: `': '"Train: `',
    '"Validação: `': '"Validation: `',
    '"Amostras treino: **{total_train:,}**  |  "': '"Train samples: **{total_train:,}**  |  "',
    '"Validação: **{total_val:,}**"': '"Validation: **{total_val:,}**"',
    '"Cluster {r.cluster_id}<br>Estações: {r.n_stations}"': '"Cluster {r.cluster_id}<br>Stations: {r.n_stations}"',
    '"Selecione uma estação na sidebar ou no mapa"': '"Select a station in the sidebar or on the map"',
    '"Data"': '"Date"',
    '"INMET observado"': '"Observed INMET"',
    '"MLP predito"': '"Predicted MLP"',
    '"Estação {estacao} — Cluster {cid}"': '"Station {estacao} — Cluster {cid}"',
    '"predictions_by_station.csv não encontrado"': '"predictions_by_station.csv not found"',
    '"Valor: %{y:.2f} m/s<extra></extra>"': '"Value: %{y:.2f} m/s<extra></extra>"',
    '"P90 global"': '"Global P90"',
    '"Distribuição por Cluster — INMET (esq.) vs MLP (dir.)"': '"Distribution by Cluster — INMET (left) vs MLP (right)"',
    '"Obs: %{x:.2f} m/s<br>"': '"Obs: %{x:.2f} m/s<br>"',
    '"Pred: %{y:.2f} m/s<extra></extra>"': '"Pred: %{y:.2f} m/s<extra></extra>"',
    '" regressão<br>"': '" regression<br>"',
    '"Observado × Predito (linha = regressão OLS)"': '"Observed vs Predicted (line = OLS regression)"',
    '"Observado — {YAXIS_WIND}"': '"Observed — {YAXIS_WIND}"',
    '"Predito — {YAXIS_WIND}"': '"Predicted — {YAXIS_WIND}"',
    '"Importância por Permutação — Cluster {cluster_id}"': '"Permutation Importance — Cluster {cluster_id}"',
    '"Queda em R²"': '"Drop in R²"',
    '"Top {TOP_N} — Cluster {cluster_id} (laranja = MLP)"': '"Top {TOP_N} — Cluster {cluster_id} (orange = MLP)"',
    'Barras agrupadas: best R² por cluster × experimento.': 'Grouped bars: best R² per cluster × experiment.',
    '"Melhor R² por cluster × experimento"': '"Best R² per cluster × experiment"',
    'Tabela com ΔR² e ΔRMSE de cada experimento vs baseline por cluster.': 'Table with ΔR² and ΔRMSE for each experiment vs baseline per cluster.',
    '"Experimento"': '"Experiment"',
    '"Melhor Modelo"': '"Best Model"',
    '"Verão (DJF)"': '"Summer (DJF)"',
    '"Outono (MAM)"': '"Autumn (MAM)"',
    '"Inverno (JJA)"': '"Winter (JJA)"',
    '"Primavera (SON)"': '"Spring (SON)"',
    'Escala divergente CVD-segura, centrada em R²=0 (vermelho=ruim ↔ azul=bom)': 'CVD-safe diverging scale, centered at R²=0 (red=bad ↔ blue=good)',
    'Heatmap experimentos (linhas) × trimestres (colunas) para um cluster.': 'Heatmap experiments (rows) × seasons (columns) for a cluster.',
    'modelo global': 'global model',
    '"Explorador MLP"': '"MLP Explorer"',
    '"Screening LazyPredict"': '"LazyPredict Screening"',
    '"Ganhos por Experimento"': '"Gains per Experiment"',
    '"Deep Learning"': '"Deep Learning"',
    '"Experimento (MLP)"': '"Experiment (MLP)"',
    '"Métrica"': '"Metric"',
    '"Screening de 43 modelos via LazyPredict por cluster espacial "': '"Screening of 43 models via LazyPredict per spatial cluster "',
    '"(treino 2000–2022 / validação 2023). "': '"(train 2000–2022 / validation 2023). "',
    '"O **MLPRegressor** (laranja) lidera em 3 de 6 clusters e aparece "': '"The **MLPRegressor** (orange) leads in 3 out of 6 clusters and appears "',
    '"no top-3 em outros 2, justificando sua escolha como modelo principal."': '"in the top-3 in 2 others, justifying its choice as the main model."',
    '"Ranking por experimento"': '"Ranking per experiment"',
    '"Comparação entre experimentos"': '"Comparison between experiments"',
    '"Experimento (Lazy)"': '"Experiment (Lazy)"',
    '"Execute ao menos dois experimentos para comparar."': '"Run at least two experiments to compare."',
    '"Baseline (referência)"': '"Baseline (reference)"',
    '"Ganhos por Experimento — melhor modelo por cluster × trimestre"': '"Gains per Experiment — best model per cluster × season"',
    '"Nenhum experimento LazyPredict ou LSTM encontrado."': '"No LazyPredict or LSTM experiments found."',
    '"Sem métricas para exibir."': '"No metrics to display."',
    '"R² de deploy (mensal)"': '"Deploy R² (monthly)"',
    '"R² bruto (validação)"': '"Raw R² (validation)"',
    '"por cluster e trimestre climático. Compara LazyPredict/MLP "': '"per cluster and climatic season. Compares LazyPredict/MLP "',
    '"estratificados por estação (incluindo o LSTM) repetem o valor "': '"stratified by season (including LSTM) repeat the value "',
    '"do modelo global nos 4 trimestres, marcados com **."': '"of the global model across the 4 seasons, marked with **."',
    '"ℹ️ Como o deep learning entra na comparação, toda a matriz "': '"ℹ️ Since deep learning is included in the comparison, the entire matrix "',
    '"usa R² bruto de validação — o LSTM não tem R² de deploy, "': '"uses raw validation R² — LSTM lacks deploy R², "',
    '"então essa é a métrica comum a todos."': '"so this is the common metric for all."',
    '"ℹ️ Usando R² bruto porque nem todos os experimentos têm "': '"ℹ️ Using raw R² because not all experiments have "',
    '"R² de deploy — troca automática para deploy quando todos "': '"deploy R² — automatic switch to deploy when all "',
    '"tiverem (comparação apples-to-apples)."': '"have it (apples-to-apples comparison)."',
    '"Linhas = experimentos (de cima para baixo, mais recentes). "': '"Rows = experiments (top to bottom, most recent). "',
    '"Azul = R² maior; vermelho = R² ≤ 0. "': '"Blue = higher R²; red = R² ≤ 0. "',
    '"** = métrica do modelo global aplicada ao trimestre."': '"** = global model metric applied to the season."',
    '"Tabela detalhada — R² e modelo por trimestre"': '"Detailed table — R² and model per season"',
    '"Trimestre"': '"Season"',
    '"R² de deploy"': '"Deploy R²"',
    '"Modelo escolhido"': '"Chosen model"',
    '"Nenhum experimento LSTM em `{LSTM_DIR}`. Copie a pasta do "': '"No LSTM experiment in `{LSTM_DIR}`. Copy the experiment folder "',
    '"experimento (ex.: `lstm_v2/`) para esse diretório."': '"(e.g., `lstm_v2/`) to this directory."',
    '"Experimento (LSTM)"': '"Experiment (LSTM)"',
    '"Curva de Loss"': '"Loss Curve"',
    '"Scatter Obs×Pred"': '"Scatter Obs×Pred"',
    '"Arquitetura & Pesos"': '"Architecture & Weights"',
    '"Série de loss não disponível como dado neste "': '"Loss series not available as data in this "',
    '"experimento — exibindo o PNG gerado no treino."': '"experiment — showing the PNG generated during training."',
    '"Sem loss_history para este cluster."': '"No loss_history for this cluster."',
    '"épocas | melhor val = "': '"epochs | best val = "',
    '"(época {best_ep})"': '"(epoch {best_ep})"',
    '"Sem predictions para este cluster."': '"No predictions for this cluster."',
    '"Sem dados para o split \'{split}\'."': '"No data for split \'{split}\'."',
    '"Observado (m/s)"': '"Observed (m/s)"',
    '"Predito (m/s)"': '"Predicted (m/s)"',
    '"Sem architecture json para este cluster."': '"No architecture json for this cluster."',
    '" parâmetros"': '" parameters"',
    '"camada"': '"layer"',
    '"média"': '"mean"',
    '"Histograma de pesos — camada"': '"Weights histogram — layer"',
    '"peso": centers, "contagem": lyr["hist_counts"]': '"weight": centers, "count": lyr["hist_counts"]',
    'Polígonos base de um cluster_id': 'Base polygons of a cluster_id',
    'Amostras treino:': 'Train samples:',
    'Validação:': 'Validation:',
    ' regressão': ' regression',
    'Importância por Permutação': 'Permutation Importance',
    'Métrica ÚNICA para toda a comparação: R² de deploy só se TODOS os': 'UNIQUE metric for the whole comparison: Deploy R² only if ALL',
    'experimentos a tiverem (comparação apples-to-apples); senão R² bruto.': 'experiments have it (apples-to-apples comparison); otherwise raw R².',
    'Métrica única em toda a matriz (ver _gains_metric). Experimentos SEM': 'Unique metric across the matrix (see _gains_metric). Experiments WITHOUT',
    'estratificação sazonal preenchem os 4 trimestres com o modelo global': 'seasonal stratification fill the 4 seasons with the global model',
    'força R² bruto ("R-Squared") em toda a matriz — usado': 'forces raw R² ("R-Squared") across the matrix — used',
    'quando há experimentos de deep learning na comparação (que só têm R²': 'when there are deep learning experiments in the comparison (which only have R²',
    'de validação), para manter tudo apples-to-apples.': 'validation), to keep everything apples-to-apples.',
    'Melhor modelo por (experimento, cluster, trimestre).': 'Best model by (experiment, cluster, season).',
    'Linhas no schema de ``build_gains_long`` a partir dos resultados LSTM.': 'Rows in the schema of ``build_gains_long`` from LSTM results.',
    'Deep learning não é estratificado por trimestre → replica o R² de': 'Deep learning is not stratified by season → replicates the R² of',
    'validação (``val_R2``) nos 4 trimestres (is_global=True → sufixo **).': 'validation (``val_R2``) in the 4 seasons (is_global=True → suffix **).',
    'Métrica sempre R² bruto de validação, comparável ao ``R-Squared`` do': 'Metric always raw validation R², comparable to ``R-Squared`` from',
    'LazyPredict (ambos avaliados no split de validação).': 'LazyPredict (both evaluated on the validation split).',
    'Deep learning na comparação → força R² bruto de validação para': 'Deep learning in comparison → force raw validation R² for',
    'todos (LSTM não tem R² de deploy), mantendo apples-to-apples.': 'all (LSTM lacks deploy R²), keeping apples-to-apples.',
    'Capturar clique em estação no mapa': 'Capture click on station in the map',
    'Delta vs baseline': 'Delta vs baseline',
    'Seletor de experimento (grava em st.session_state': 'Experiment selector (saves to st.session_state',
    'lido pela sidebar para carregar os dados deste experimento).': 'read by the sidebar to load the data for this experiment).',
    'Linha 1: Mapa + Série temporal': 'Row 1: Map + Time series',
    'Linha 2: Distribuição + Scatter': 'Row 2: Distribution + Scatter',
    'Linha 3: Métricas + Importância': 'Row 3: Metrics + Importance',
    '"Ranking"': '"Ranking"',
    '"Rank"': '"Rank"',
}

for k, v in replacements.items():
    content = content.replace(k, v)

with open("app.py", "w") as f:
    f.write(content)

print("Translation applied!")
